FROM nginx:alpine

# Remove default nginx files
RUN rm -rf /usr/share/nginx/html/*

# Copy only required frontend files
COPY . /usr/share/nginx/html

# Custom nginx config
RUN printf "server {\n\
    listen 8080;\n\
    server_name localhost;\n\
    root /usr/share/nginx/html;\n\
    index index.html;\n\
    location / {\n\
        try_files \$uri \$uri/ /index.html;\n\
    }\n\
}" > /etc/nginx/conf.d/default.conf

# Run as non-root (optional but good)
RUN adduser -D appuser
USER appuser

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]