version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=devops
      - MONGO_INITDB_ROOT_PASSWORD=karthi2004
    volumes:
      - mongo-data:/data/db

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "5005:5000"
    environment:
      - MONGO_HOST=mongo
      - MONGO_USER=devops
      - MONGO_PASS=karthi2004
      - JWT_SECRET=secret123
    depends_on:
      - mongo

  appointment-service:
    build: ./appointment-service
    container_name: appointment-service
    ports:
      - "5006:5006"
    environment:
      - MONGO_HOST=mongo
      - MONGO_USER=devops
      - MONGO_PASS=karthi2004
      - JWT_SECRET=secret123
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8081:8080"  # Changed host port to 8081 to avoid conflict
    environment:
      - REACT_APP_AUTH_URL=http://localhost:5005
      - REACT_APP_APPOINTMENT_URL=http://localhost:5006
    depends_on:
      - auth-service
      - appointment-service

volumes:
  mongo-data: