image: pikachu7/api-gateway:v1
imagePullPolicy: Always
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007