image: pikachu7/appointment-service:v1.26
imagePullPolicy: Always
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
spec:
  type: ClusterIP
  selector:
    app: appointment
  ports:
    - port: 5002
      targetPort: 5002