apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment
  template:
    metadata:
      labels:
        app: appointment
    spec:
      containers:
      - name: appointment
        image: appointment-service
        ports:
        - containerPort: 5001