image: pikachu7/auth-service:v1.26
imagePullPolicy: Always
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - port: 5001
      targetPort: 5001